source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
install! 'cocoapods', :disable_input_output_paths => true
use_frameworks!

def tx_UGCKit(subName)
 pod 'UGCKit', :path => 'UGCKit/UGCKit.podspec', :subspecs => ["#{subName}"]
end

target 'XiaoShiPinApp' do
  tx_UGCKit 'UGC'
  pod 'BeautySettingKit', :path => 'BeautySettingKit/BeautySettingKit.podspec'
  pod 'xmagickit', :path => 'xmagickit/xmagickit.podspec'
  pod "AFNetworking"
  pod "MJRefresh"
  pod "MBProgressHUD"
  pod "SDWebImage"
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end




